name: russlayton
favicon: null
layout_spectrum: 0.99559
typography_spectrum: 0.48043536650948226
title: 'el toro loco :: Art of Russ Layton'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05354112549684942
  lightness: 0.23899645544588566
  saturation: 0.881004644325003
  rhythmicContrast: 0.4363108540419489
purpose: []
